---
- name: Add the webupd8 APT repository key (Ajoute la cles de l empacteur)
  tags:
    - java
    - java-webupd8
  become: true
  apt_key: keyserver=keyserver.ubuntu.com id=EEA14886 state=present
  # Use a static file because right now using just an ID fails

- name: Add the webupd8 APT repository (Ajoute le depot)
  tags:
    - java
    - java-webupd8
  become: true
  apt_repository: repo="deb http://ppa.launchpad.net/webupd8team/java/ubuntu precise main" state=present
